//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deltax
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeltaXDBContext : DbContext
    {
        public DeltaXDBContext()
            : base("name=DeltaXDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<ActorMovie> ActorMovies { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Producer> Producers { get; set; }
    
        public virtual int usp_ActorID(ObjectParameter actorID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActorID", actorID);
        }
    
        public virtual int usp_ActorMovie(ObjectParameter iD)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActorMovie", iD);
        }
    
        public virtual int usp_MovieID(ObjectParameter movieID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MovieID", movieID);
        }
    
        public virtual int usp_ProducerID(ObjectParameter producerID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ProducerID", producerID);
        }
    }
}
