//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deltax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.ActorMovies = new HashSet<ActorMovie>();
        }
    
        public string MovieId { get; set; }
        public string MovieName { get; set; }
        public Nullable<short> YearOfRelease { get; set; }
        public string Plot { get; set; }
        public byte[] Poster { get; set; }
        public string ProducerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorMovie> ActorMovies { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
